In [1]:
import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

C:\Users\subham.jalan\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
census_2001 = pd.read_csv("pc01_vd_clean_shrid.csv")  # Replace with actual 2001 data path
census_2011 = pd.read_csv("pc11_vd_clean_shrid.csv")  # Replace with actual 2011 data path

In [13]:
print(census_2001.shape)
print(census_2011.shape)

(527920, 110)
(588973, 284)

In [7]:
merged_data = pd.merge(census_2001, census_2011, on="shrid2")

In [ ]:
merged_data[""]

In [14]:
merged_data["population_change_pct"] = (
    (merged_data["pc11_vd_t_p"] - merged_data["pc01_vd_t_p"])
    / merged_data["pc01_vd_t_p"]
) * 100

# Ca

In [ ]:
merged_data["total_schools_2011"] = (
    merged_data["pc11_vd_p_sch_gov"]
    + merged_data["pc11_vd_m_sch_gov"]
    + merged_data["pc11_vd_s_sch_gov"]
    + merged_data["pc11_vd_p_p_sch_gov"]
    + merged_data["pc11_vd_p_p_sch_priv"]
    + merged_data["pc11_vd_p_sch_priv"]
    + merged_data["pc11_vd_m_sch_priv"]
    + merged_data["pc11_vd_s_sch_priv"]
    + merged_data["pc11_vd_s_s_sch_gov"]
    + merged_data["pc11_vd_s_s_sch_priv"]
    + merged_data["pc11_vd_voct_sch_gov"]
    + merged_data["pc11_vd_voct_sch_priv"]
    + merged_data["pc11_vd_disab_sch_gov"]
    + merged_data["pc11_vd_disab_sch_priv"]
    + merged_data["pc11_vd_a_s_coll_gov"]
    + merged_data["pc11_vd_a_s_coll_priv"]
    + merged_data["pc11_vd_engg_coll_gov"]
    + merged_data["pc11_vd_engg_coll_priv"]
    + merged_data["pc11_vd_medi_coll_gov"]
    + merged_data["pc11_vd_medi_coll_priv"]
)
merged_data["total_schools_2011"] = new_df.sum(axis=1)
# formatted version of the above line with line breaks

In [27]:
merged_data

,shrid2,pc01_vd_area,pc01_vd_t_hh,pc01_vd_t_p,pc01_vd_t_m,pc01_vd_t_f,pc01_vd_sc_p,pc01_vd_sc_m,pc01_vd_sc_f,pc01_vd_st_p,...,land_flag,dist_flag,_mean_p_miss_y,_core_p_miss_y,_target_weight_share_y,_target_group_max_weight_share_y,population_change,population_change_pct,total_schools,total_schools_2011
0,11-01-001-00001-000002,237.60,178.0,2550.0,1670.0,880.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.000000,0.0,1.0,1.0,0.478431,47.843137,9.0,9.0
1,11-01-001-00001-000005,355.30,334.0,3913.0,1934.0,1979.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.000000,0.0,1.0,1.0,0.342959,34.295937,10.0,10.0
2,11-01-001-00001-000006,146.50,153.0,2423.0,1816.0,607.0,0.0,0.0,0.0,188.0,...,1.0,1.0,0.000000,0.0,1.0,1.0,0.238547,23.854726,6.0,6.0
3,11-01-001-00001-000007,130.30,101.0,740.0,385.0,355.0,0.0,0.0,0.0,253.0,...,1.0,1.0,0.000000,0.0,1.0,1.0,0.770270,77.027027,7.0,7.0
4,11-01-001-00001-000008,85.00,5.0,31.0,18.0,13.0,0.0,0.0,0.0,10.0,...,1.0,1.0,0.000000,0.0,1.0,1.0,3.161290,316.129032,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519857,11-33-633-05902-644662,3739.75,1881.0,6510.0,3273.0,3237.0,1267.0,630.0,637.0,7.0,...,1.0,1.0,0.017352,0.0,1.0,1.0,-0.033026,-3.302611,14.0,14.0
519858,11-33-633-05902-644668,5360.26,2203.0,7923.0,4028.0,3895.0,2243.0,1131.0,1112.0,0.0,...,1.0,1.0,0.009204,0.0,1.0,1.0,-0.002146,-0.214565,21.0,21.0
519859,11-33-633-05902-644670,5135.00,2520.0,8603.0,4365.0,4238.0,2188.0,1137.0,1051.0,0.0,...,1.0,1.0,0.010934,0.0,1.0,1.0,0.073579,7.357898,19.0,19.0
519860,11-33-633-05902-644678,4401.95,1574.0,5587.0,2830.0,2757.0,1322.0,675.0,647.0,0.0,...,1.0,1.0,0.009322,0.0,1.0,1.0,0.018973,1.897261,15.0,15.0
519861,11-33-633-05902-644691,2741.81,2245.0,8294.0,4123.0,4171.0,3705.0,1853.0,1852.0,249.0,...,1.0,1.0,0.000000,0.0,1.0,1.0,0.086207,8.620690,25.0,25.0

In [28]:
# new df with following cols
''' 
pc01_vd_p_sch
pc01_vd_m_sch
pc01_vd_s_sch
pc01_vd_s_s_sch
pc01_vd_ind_sch
pc01_vd_tr_sch
pc01_vd_adlt_lt_ct
pc01_vd_oth_sch
pc01_vd_college
'''
new_df = merged_data[["pc01_vd_p_sch", "pc01_vd_m_sch", "pc01_vd_s_sch", "pc01_vd_s_s_sch", "pc01_vd_ind_sch", "pc01_vd_tr_sch", "pc01_vd_adlt_lt_ct", "pc01_vd_oth_sch", "pc01_vd_college"]]

In [29]:
merged_data["total_schools_2001"] = new_df.sum(axis=1)

In [30]:
merged_data[['total_schools_2001', 'total_schools_2011']]

        total_schools_2001  total_schools_2011
0                      8.0                 9.0
1                      5.0                10.0
2                      4.0                 6.0
3                      3.0                 7.0
4                      3.0                 4.0
...                    ...                 ...
519857                12.0                14.0
519858                 9.0                21.0
519859                12.0                19.0
519860                 5.0                15.0
519861                11.0                25.0

[519860 rows x 2 columns]

In [31]:
merged_data["total_schools_change"] = merged_data["total_schools_2011"] - merged_data["total_schools_2001"]

merged_data["num_hospitals_change"] = merged_data["pc11_vd_all_hosp"] + merged_data["pc11_vd_vet_hosp"] - merged_data["pc01_vd_hosp"]
merged_data["electricity_access_change"] = (
    merged_data["pc11_vd_power_all"] - merged_data["pc01_vd_power_supl"]
)

In [33]:
merged_data[['total_schools_change', 'num_hospitals_change', 'electricity_access_change']]
merged_data.dropna(subset=['population_change_pct', 'total_schools_change', 'num_hospitals_change', 'electricity_access_change'], inplace=True)

In [34]:
merged_data.shape

(516766, 401)

In [37]:

# Define independent variables (changes in factors)
independent_vars = [
    "total_schools_change",
    "num_hospitals_change",
    "electricity_access_change",
]

# Prepare data for regression
X = merged_data[independent_vars]  # Changes in independent variables
y = merged_data["population_change_pct"]  # Dependent variable: population change

# Handle missing values (if any)
X = X.fillna(0)
y = y.fillna(0)

In [38]:

# Add a constant for the intercept
X = sm.add_constant(X)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((413412, 4), (103354, 4), (413412,), (103354,))

In [40]:

# Fit the regression model
model = sm.OLS(y_train, X_train).fit()

# Print the regression summary
print("Regression Model Summary:")
print(model.summary())

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error on Test Set: {mse:.2f}")

Regression Model Summary:
                              OLS Regression Results
=================================================================================
Dep. Variable:     population_change_pct   R-squared:                       0.000
Model:                               OLS   Adj. R-squared:                  0.000
Method:                    Least Squares   F-statistic:                     30.19
Date:                   Thu, 05 Dec 2024   Prob (F-statistic):           1.67e-19
Time:                           02:37:35   Log-Likelihood:            -3.0689e+06
No. Observations:                 413412   AIC:                         6.138e+06
Df Residuals:                     413408   BIC:                         6.138e+06
Df Model:                              3
Covariance Type:               nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        26.2262      0.706     37.138      0.000      24.842      27.610
total_schools_change          1.4858      0.171      8.686      0.000       1.151       1.821
num_hospitals_change         -4.3067      1.914     -2.250      0.024      -8.058      -0.556
electricity_access_change     4.3374      1.241      3.495      0.000       1.905       6.770
===============================================================================
Omnibus:                  2183583.238   Durbin-Watson:                    1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   141512563889268.219
Skew:                         262.738   Prob(JB):                          0.00
Kurtosis:                   90639.741   Cond. No.                          11.7
===============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mean Squared Error on Test Set: 35928.05